# Builder Stage --------------------------------------------
FROM node:18-alpine AS builder

WORKDIR /usr/src/next
COPY ./package.json /usr/src/next

RUN npm install
COPY . .

RUN npm run build


# Nginx Stage --------------------------------------------
FROM nginx:alpine

COPY ./.next /usr/src/next/.next
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]